# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2e2f9321717cd5546fd7185240384a902aca51e92d48716592f8849280c7e9284bc0dd59a3f4ade84be759bec1727ce97c0b3bcee3f2131be70dea60f9695f0

test:
  secret_key_base: e236fa76f587c2e7fcc87399f8cb7649fb3fabfeaa9cdffa2e0a480acf21a0f7504987143a0b4f3d72d27ce95a4019bec615d94eef60006e827ba8f6088277cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
